In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../geography.csv')
df.head()

     zip       city region      district
0  15201  Hai Phong   East  District #13
1  15202     Phu Ly   East  District #13
2  15203   Viet Tri   East  District #13
3  15204  Bac Giang   East  District #13
4  15205  Bac Giang   East  District #13

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39948 entries, 0 to 39947
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   zip       39948 non-null  int64
 1   city      39948 non-null  str
 2   region    39948 non-null  str
 3   district  39948 non-null  str
dtypes: int64(1), str(3)
memory usage: 1.2 MB

In [4]:
#Kiểm tra thử 
df["zip"].is_unique

True

In [5]:
# Kiểm tra thử city có bị trống hay không ?
df[(df["city"] == "")]

Empty DataFrame
Columns: [zip, city, region, district]
Index: []

In [6]:
# Kiểm tra thử region có bị trống hay không ?
df[(df["region"] == "")]

Empty DataFrame
Columns: [zip, city, region, district]
Index: []

In [7]:
# Kiểm tra thử district có bị trống hay không ?
df[(df["district"] == "")]

Empty DataFrame
Columns: [zip, city, region, district]
Index: []

In [8]:
df.to_csv("../SilverData/geography.csv", index=False)